[package]
name = "starknet_api"
version = "0.6.0-rc2"
edition = "2021"
repository = "https://github.com/starkware-libs/starknet-api"
license = "Apache-2.0"
license-file = "LICENSE"
description = "Starknet Rust types related to computation and execution."

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_json/std",
    "indexmap/std",
    "starknet-crypto/std",
    "thiserror"
]
testing = ["std"]

[dependencies]
cairo-lang-starknet = { version = "2.4.0-rc2", default-features = false }
derive_more = "0.99.17"
hex = "0.4.3"
hashbrown = { version = "0.14.0", features = ["serde"] }
indexmap = { version = "1.9.2", features = ["serde"], default-features = false }
once_cell = "1.17.1"
primitive-types = { version = "0.12.1", features = ["serde"] }
serde = { version = "1.0.130", features = ["alloc", "derive", "rc"], default-features = false }
serde_json = { version = "1.0.81", features = [
    "arbitrary_precision",
    "alloc",
], default-features = false }
starknet-crypto = { version = "0.5.1", default-features = false, features = [
    "signature-display",
    "alloc",
] }
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = { version = "1.0.31", optional = true}
thiserror-no-std = { version = "2.0.2", default-features = false }
cfg-if = "1.0.0"

[dev-dependencies]
assert_matches = "1.5.0"
